name: example
description: Example for ross_lints

publish_to: 'none'

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  ross_lints:
    git:
      url: git://github.com/RossHS/ross_lint_ruleset