name: ross_lints
description: My lints ruleset for Flutter projects
repository: https://github.com/RossHS/ross_lint_ruleset
version: 2.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter_lints: ^2.0.1