name: ross_lints
description: My lints ruleset for Flutter projects
repository: https://github.com/RossHS/ross_lint_ruleset
version: 6.0.0

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter_lints: ^6.0.0